title: David Duyff
email: davidduyff@gmail.com
description: >- 
  Mijn persoonlijke website.
baseurl: "/"
url: "https://davidduyff.nl"
github_username:  ffyud

# Build settings
theme: paloma-jekyll

permalink: /:title/

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock